// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddArticleRequest struct {
	TagId         int    `json:"tag_id"`                   // 必填
	Title         string `json:"title"`                    // 必填
	Desc          string `json:"desc"`                     // 必填
	Content       string `json:"content"`                  // 必填
	CreatedBy     string `json:"created_by"`               // 必填
	CoverImageUrl string `json:"cover_image_url,optional"` // 可选
	State         int    `json:"state,optional"`           // 可选
}

type AddTagRequest struct {
	Name      string `json:"name"`           // 必填
	CreatedBy string `json:"created_by"`     // 必填
	State     int    `json:"state,optional"` // 可选
}

type Article struct {
	Id            int    `json:"id"`
	TagId         int    `json:"tag_id"`
	Title         string `json:"title"`
	Desc          string `json:"desc"`
	Content       string `json:"content"`
	CoverImageUrl string `json:"cover_image_url,optional"`
	State         int    `json:"state,optional"`
	CreatedBy     string `json:"created_by,optional"`
	ModifiedBy    string `json:"modified_by,optional"`
}

type DeleteArticleRequest struct {
	Id int `path:"id"`
}

type DeleteTagRequest struct {
	Id int `path:"id"`
}

type EditArticleRequest struct {
	Id            int    `path:"id"`                       //必填
	TagId         int    `json:"tag_id"`                   // 必填
	Title         string `json:"title"`                    // 必填
	Desc          string `json:"desc"`                     // 必填
	Content       string `json:"content"`                  // 必填
	ModifiedBy    string `json:"modified_by"`              // 必填
	CoverImageUrl string `json:"cover_image_url,optional"` // 可选
	State         int    `json:"state,optional"`           // 可选
}

type EditTagRequest struct {
	Id         int    `path:"id"`
	Name       string `json:"name"`           // 必填
	ModifiedBy string `json:"modified_by"`    // 必填
	State      int    `json:"state,optional"` // 可选
}

type ExportTagRequest struct {
	Name  string `json:"name,optional"`  // 可选
	State int    `json:"state,optional"` // 可选
}

type ExportTagResponse struct {
	Code          int    `json:"code"`
	Msg           string `json:"msg"`
	ExportUrl     string `json:"export_url"`
	ExportSaveUrl string `json:"export_save_url"`
}

type GenerateArticlePosterResponse struct {
	PosterUrl     string `json:"poster_url"`
	PosterSaveUrl string `json:"poster_save_url"`
}

type GetArticleRequest struct {
	Id int `path:"id"` //必填
}

type GetArticlesRequest struct {
	State    int `json:"state,optional"`     // 可选，0: 草稿，1: 已发布
	TagId    int `json:"tag_id,optional"`    // 可选，标签ID
	PageNum  int `json:"page_num,optional"`  // 分页参数
	PageSize int `json:"page_size,optional"` // 分页参数
}

type GetArticlesResponse struct {
	Code     int         `json:"code"`
	Msg      string      `json:"msg"`
	Data     interface{} `json:"data,optional"` // 文章列表
	Total    int64       `json:"total"`
	PageNum  int         `json:"page_num"`
	PageSize int         `json:"page_size"`
}

type GetTagsRequest struct {
	Name     string `form:"name,optional" json:"name,optional"`           // 从查询参数解析
	State    int    `form:"state,optional" json:"state,optional"`         // 从查询参数解析
	PageNum  int    `form:"page_num,optional" json:"page_num,optional"`   // 分页参数
	PageSize int    `form:"page_size,optional" json:"page_size,optional"` // 分页参数
}

type GetTagsResponse struct {
	Code     int         `json:"code"`
	Msg      string      `json:"msg"`
	Data     interface{} `json:"data,optional"`
	Total    int64       `json:"total"`
	PageNum  int         `json:"page_num"`
	PageSize int         `json:"page_size"`
}

type ImportTagRequest struct {
	File string `json:"file"` // 表示 multipart 文件，go-zero 不直接处理文件流，这里用 string 占位
}

type LoginRequest struct {
	Username string `json:"username"` // 必填
	Password string `json:"password"` // 必填
}

type LoginResponse struct {
	Code    int    `json:"code"`
	Msg     string `json:"msg"`
	Token   string `json:"token"`
	Expires int    `json:"expiration"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,optional"` // Data 可选，视接口而定
}

type Tag struct {
	Id         int    `json:"id"`
	Name       string `json:"name"`
	CreatedBy  string `json:"created_by,optional"`
	ModifiedBy string `json:"modified_by,optional"`
	State      int    `json:"state,optional"`
}

type UpLoadImageRequest struct {
	UserId int64  `json:"user_id" form:"user_id"` // 用户ID，可选
	Image  []byte `json:"image" form:"image"`     // 图片二进制数据
}

type UpLoadImageResponse struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	ImageURL string `json:"image_url"` // 图片访问路径
}

type User struct {
	Id       int    `gorm:"primaryKey;column:id"`
	Username string `gorm:"column:username"`
	Password string `gorm:"column:password"` // 实际应加密存储
}
