// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	tag "github.com/3Eeeecho/go-zero-blog/app/tag/cmd/api/internal/handler/tag"
	"github.com/3Eeeecho/go-zero-blog/app/tag/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取标签列表
				Method:  http.MethodGet,
				Path:    "/tag",
				Handler: tag.GetTagsHandler(serverCtx),
			},
			{
				// 新增文章标签
				Method:  http.MethodPost,
				Path:    "/tag",
				Handler: tag.AddTagHandler(serverCtx),
			},
			{
				// 修改文章标签
				Method:  http.MethodPut,
				Path:    "/tag/:id",
				Handler: tag.EditTagHandler(serverCtx),
			},
			{
				// 删除文章标签
				Method:  http.MethodDelete,
				Path:    "/tag/:id",
				Handler: tag.DeleteTagHandler(serverCtx),
			},
			{
				// 导出标签信息
				Method:  http.MethodPost,
				Path:    "/tag/export",
				Handler: tag.ExportTagHandler(serverCtx),
			},
			{
				// 导入标签信息
				Method:  http.MethodPost,
				Path:    "/tag/import",
				Handler: tag.ImportTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
