// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddTagRequest struct {
	Name      string `json:"name"`           // 必填
	CreatedBy string `json:"created_by"`     // 必填
	State     int32  `json:"state,optional"` // 可选
}

type DeleteTagRequest struct {
	Id int64 `json:"id"`
}

type EditTagRequest struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`        // 必填
	ModifiedBy string `json:"modified_by"` // 必填
}

type ExportTagRequest struct {
	Name  string `json:"name,optional"`  // 可选
	State int32  `json:"state,optional"` // 可选
}

type ExportTagResponse struct {
	Msg           string `json:"msg"`
	ExportUrl     string `json:"export_url"`
	ExportSaveUrl string `json:"export_save_url"`
}

type GetTagsRequest struct {
	Name     string ` json:"name,optional"`      // 从查询参数解析
	State    int32  ` json:"state,optional"`     // 从查询参数解析
	PageNum  int64  `" json:"page_num,optional"` // 分页参数
	PageSize int64  ` json:"page_size,optional"` // 分页参数
}

type GetTagsResponse struct {
	Msg      string      `json:"msg"`
	Data     interface{} `json:"data,optional"`
	Total    int64       `json:"total"`
	PageNum  int64       `json:"page_num"`
	PageSize int64       `json:"page_size"`
}

type ImportTagRequest struct {
}

type Response struct {
	Msg string `json:"msg"`
}

type Tag struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	CreatedBy  string `json:"created_by,optional"`
	ModifiedBy string `json:"modified_by,optional"`
	State      int32  `json:"state,optional"`
}
