// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	article "github.com/3Eeeecho/go-zero-blog/internal/handler/article"
	tag "github.com/3Eeeecho/go-zero-blog/internal/handler/tag"
	upload "github.com/3Eeeecho/go-zero-blog/internal/handler/upload"
	user "github.com/3Eeeecho/go-zero-blog/internal/handler/user"
	"github.com/3Eeeecho/go-zero-blog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取文章列表
				Method:  http.MethodGet,
				Path:    "/api/v1/articles",
				Handler: article.GetArticlesHandler(serverCtx),
			},
			{
				// 新增一篇文章
				Method:  http.MethodPost,
				Path:    "/api/v1/articles",
				Handler: article.AddArticleHandler(serverCtx),
			},
			{
				// 获取单篇文章的详细信息
				Method:  http.MethodGet,
				Path:    "/api/v1/articles/:id",
				Handler: article.GetArticleHandler(serverCtx),
			},
			{
				// 修改文章
				Method:  http.MethodPut,
				Path:    "/api/v1/articles/:id",
				Handler: article.EditArticleHandler(serverCtx),
			},
			{
				// 删除文章
				Method:  http.MethodDelete,
				Path:    "/api/v1/articles/:id",
				Handler: article.DeleteArticleHandler(serverCtx),
			},
			{
				// 生成文章海报
				Method:  http.MethodGet,
				Path:    "/api/v1/articles/poster/generate",
				Handler: article.GenerateArticlePosterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取标签列表
				Method:  http.MethodGet,
				Path:    "/api/v1/tags",
				Handler: tag.GetTagsHandler(serverCtx),
			},
			{
				// 新增文章标签
				Method:  http.MethodPost,
				Path:    "/api/v1/tags",
				Handler: tag.AddTagHandler(serverCtx),
			},
			{
				// 修改文章标签
				Method:  http.MethodPut,
				Path:    "/api/v1/tags/:id",
				Handler: tag.EditTagHandler(serverCtx),
			},
			{
				// 删除文章标签
				Method:  http.MethodDelete,
				Path:    "/api/v1/tags/:id",
				Handler: tag.DeleteTagHandler(serverCtx),
			},
			{
				// 导出标签信息
				Method:  http.MethodPost,
				Path:    "/api/v1/tags/export/tag",
				Handler: tag.ExportTagHandler(serverCtx),
			},
			{
				// 导入标签信息
				Method:  http.MethodPost,
				Path:    "/api/v1/tags/import/tag",
				Handler: tag.ImportTagHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 上传图片
				Method:  http.MethodPost,
				Path:    "/upload/image",
				Handler: upload.UpLoadImageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取授权 Token
				Method:  http.MethodGet,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
	)
}
