// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddArticleRequest struct {
	TagId   int64  `json:"tag_id"`  // 必填
	Title   string `json:"title"`   // 必填
	Desc    string `json:"desc"`    // 必填
	Content string `json:"content"` // 必填
}

type Article struct {
	Id         int64  `json:"id"`
	TagId      int64  `json:"tag_id"`
	Title      string `json:"title"`
	Desc       string `json:"desc"`
	Content    string `json:"content"`
	State      int32  `json:"state,optional"`
	CreatedBy  int64  `json:"created_by,optional"`
	ModifiedBy int64  `json:"modified_by,optional"`
}

type ArticleCommonResponse struct {
	Msg string `json:"msg"`
}

type Comment struct {
	Id        int64     `json:"id"`
	ArticleId int64     `json:"article_id"`
	UserId    int64     `json:"user_id"`
	Content   string    `json:"content"`
	ParentId  int64     `json:"parent_id,optional"`
	Children  []Comment `json:"children,optional"` // 嵌套回复
}

type CommentReq struct {
	ArticleId int64  `json:"article_id"`
	Content   string `json:"content"`
	ParentId  int64  `json:"parent_id,optional"` // 可选，回复某条评论
}

type CommentResp struct {
	Msg string `json:"msg"`
}

type DeleteArticleRequest struct {
	Id int64 `path:"id"`
}

type EditArticleRequest struct {
	Id      int64  `json:"id"`             //必填
	TagId   int64  `json:"tag_id"`         // 必填
	Title   string `json:"title"`          // 必填
	Desc    string `json:"desc"`           // 必填
	Content string `json:"content"`        // 必填
	State   int32  `json:"state,optional"` // 可选
}

type GetArticleRequest struct {
	Id int64 `path:"id"` //必填
}

type GetArticleResponse struct {
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,optional"`
}

type GetArticlesRequest struct {
	TagId    int64 `json:"tag_id,optional"`    // 可选，标签ID
	PageNum  int   `json:"page_num,optional"`  // 分页参数
	PageSize int   `json:"page_size,optional"` // 分页参数
}

type GetArticlesResponse struct {
	Msg      string      `json:"msg"`
	Data     interface{} `json:"data,optional"` // 文章列表
	Total    int64       `json:"total"`
	PageNum  int         `json:"page_num"`
	PageSize int         `json:"page_size"`
}

type GetCommentsReq struct {
	ArticleId int64 `json:"article_id"`
	PageNum   int64 `json:"page_num,default=1"`
	PageSize  int64 `json:"page_size,default=10"`
}

type GetCommentsResp struct {
	Msg      string    `json:"msg"`
	Comments []Comment `json:"comments"`
	Total    int64     `json:"total"`
}

type GetPendingArticlesRequest struct {
	PageNum  int `json:"page_num,optional"`  // 分页参数
	PageSize int `json:"page_size,optional"` // 分页参数
}

type GetPendingArticlesResponse struct {
	Msg      string      `json:"msg"`
	Data     interface{} `json:"data,optional"` // 文章列表
	Total    int64       `json:"total"`
	PageNum  int         `json:"page_num"`
	PageSize int         `json:"page_size"`
}

type LikeArticleRequest struct {
	Article_id int64 `path:"id"` // 文章 ID
}

type ReviewArticleRequest struct {
	Id       int64 `json:"id"`
	Approved bool  `json:"approved"`
}

type SubmitArticleRequest struct {
	Id int64 `json:"id"`
}
