// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	article "github.com/3Eeeecho/go-zero-blog/app/article/cmd/api/internal/handler/article"
	"github.com/3Eeeecho/go-zero-blog/app/article/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取文章列表
				Method:  http.MethodGet,
				Path:    "/articles",
				Handler: article.GetArticlesHandler(serverCtx),
			},
			{
				// 新增一篇文章
				Method:  http.MethodPost,
				Path:    "/articles",
				Handler: article.AddArticleHandler(serverCtx),
			},
			{
				// 修改文章
				Method:  http.MethodPut,
				Path:    "/articles",
				Handler: article.EditArticleHandler(serverCtx),
			},
			{
				// 获取单篇文章的详细信息
				Method:  http.MethodGet,
				Path:    "/articles/:id",
				Handler: article.GetArticleHandler(serverCtx),
			},
			{
				// 删除文章
				Method:  http.MethodDelete,
				Path:    "/articles/:id",
				Handler: article.DeleteArticleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
