// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type BaseResponse struct {
	Msg string `json:"msg"`
}

type LoginRequest struct {
	Username string `json:"username"` // 必填
	Password string `json:"password"` // 必填
}

type LoginResponse struct {
	Token   string `json:"token"`
	Expires int    `json:"expiration"`
}

type RegisterRequest struct {
	Username string `json:"username"` // 必填
	Password string `json:"password"` // 必填
}

type RegisterResponse struct {
	Token   string `json:"token"`
	Expires int    `json:"expiration"`
}

type UpdatePasswordRequest struct {
	NewPassword string `json:"password"` // 加密后的密码
}

type UpdatePasswordResponse struct {
	BaseResponse
}

type UpdateUserRoleRequest struct {
	Id   int    `json:"id"`
	Role string `json:"role"` // "user", "author", "admin"
}

type UpdateUserRoleResponse struct {
	Msg string `json:"msg"`
}

type UpdateUsernameRequest struct {
	NewUsername string `json:"username"`
}

type UpdateUsernameResponse struct {
	BaseResponse
}

type User struct {
	Id       int    `gorm:"primaryKey;column:id"`
	Username string `gorm:"column:username"`
	Password string `gorm:"column:password"` // 实际应加密存储
	Role     string `gorm:"column:role"`
}
