// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type BaseResponse struct {
	Msg string `json:"msg"`
}

type GetUserInfoRequest struct {
	Id int64 `path:"id"`
}

type GetUserInfoResponse struct {
	User UserInfo `json:"userinfo"`
}

type GetUsersInfoRequest struct {
	Ids []int64 `json:"ids,required"`
}

type GetUsersInfoResponse struct {
	Users []UserInfo `json:"usersinfo"`
}

type LoginRequest struct {
	Username string `json:"username"` // 必填
	Password string `json:"password"` // 必填
}

type LoginResponse struct {
	Token   string `json:"token"`
	Expires int64  `json:"expiration"`
}

type RegisterRequest struct {
	Username string `json:"username"` // 必填
	Password string `json:"password"` // 必填
	Nickname string `json:"nickname"` // 必填
}

type RegisterResponse struct {
	Token   string `json:"token"`
	Expires int64  `json:"expiration"`
}

type UpdateNicknameRequest struct {
	NewNickname string `json:"nickname"`
}

type UpdateNicknameResponse struct {
	BaseResponse
}

type UpdatePasswordRequest struct {
	NewPassword string `json:"password"` // 加密后的密码
}

type UpdatePasswordResponse struct {
	BaseResponse
}

type User struct {
	Id       int64  `gorm:"primaryKey;column:id"`
	Username string `gorm:"column:username"`
	Password string `gorm:"column:password"` // 实际应加密存储
	Role     string `gorm:"column:role"`
	Nickname string `gorm:colunm:nickname"`
}

type UserInfo struct {
	Id       int64  `gorm:"primaryKey;column:id"`
	Nickname string `gorm:column:nickname"`
}
