// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: article.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应结构
type ArticleCommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleCommonResponse) Reset() {
	*x = ArticleCommonResponse{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleCommonResponse) ProtoMessage() {}

func (x *ArticleCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleCommonResponse.ProtoReflect.Descriptor instead.
func (*ArticleCommonResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleCommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Article 结构体，表示文章实体
type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagId         int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	State         int32                  `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"` // 可选，0: 草稿,1: 待审核,2:审核成功,3:审核失败
	CreatedBy     int64                  `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedBy    int64                  `protobuf:"varint,8,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Article) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Article) GetModifiedBy() int64 {
	if x != nil {
		return x.ModifiedBy
	}
	return 0
}

// --- GetArticle ---
type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 路径参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Article               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 返回单篇具体文章
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleResponse) GetData() *Article {
	if x != nil {
		return x.Data
	}
	return nil
}

// --- GetArticles ---
type GetArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`          // 可选，标签ID
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    // 分页参数
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesRequest) Reset() {
	*x = GetArticlesRequest{}
	mi := &file_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesRequest) ProtoMessage() {}

func (x *GetArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticlesRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *GetArticlesRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetArticlesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Article             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`                          // 返回文章列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总条数
	PageNum       int64                  `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    // 当前页码
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesResponse) Reset() {
	*x = GetArticlesResponse{}
	mi := &file_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesResponse) ProtoMessage() {}

func (x *GetArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{5}
}

func (x *GetArticlesResponse) GetData() []*Article {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetArticlesResponse) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetArticlesResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPendingArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PageNum       int64                  `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingArticlesRequest) Reset() {
	*x = GetPendingArticlesRequest{}
	mi := &file_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingArticlesRequest) ProtoMessage() {}

func (x *GetPendingArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetPendingArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{6}
}

func (x *GetPendingArticlesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPendingArticlesRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetPendingArticlesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPendingArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Article             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageNum       int64                  `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    // 当前页码
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingArticlesResponse) Reset() {
	*x = GetPendingArticlesResponse{}
	mi := &file_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingArticlesResponse) ProtoMessage() {}

func (x *GetPendingArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetPendingArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingArticlesResponse) GetData() []*Article {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetPendingArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPendingArticlesResponse) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetPendingArticlesResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// --- AddArticle ---
type AddArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`             // 必填
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                           // 必填
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`                             // 必填
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                       // 必填
	CreatedBy     int64                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // 必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticleRequest) Reset() {
	*x = AddArticleRequest{}
	mi := &file_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleRequest) ProtoMessage() {}

func (x *AddArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleRequest.ProtoReflect.Descriptor instead.
func (*AddArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{8}
}

func (x *AddArticleRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *AddArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddArticleRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AddArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddArticleRequest) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

// --- EditArticle ---
type EditArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 路径参数
	TagId         int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`                // 可选
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                              // 可选
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`                                // 可选
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                          // 可选
	ModifiedBy    int64                  `protobuf:"varint,6,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"` // 可选
	State         int32                  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`                             // 可选
	UserId        int64                  `protobuf:"varint,8,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditArticleRequest) Reset() {
	*x = EditArticleRequest{}
	mi := &file_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditArticleRequest) ProtoMessage() {}

func (x *EditArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditArticleRequest.ProtoReflect.Descriptor instead.
func (*EditArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{9}
}

func (x *EditArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditArticleRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *EditArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditArticleRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *EditArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditArticleRequest) GetModifiedBy() int64 {
	if x != nil {
		return x.ModifiedBy
	}
	return 0
}

func (x *EditArticleRequest) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *EditArticleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// --- DeleteArticle ---
type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 路径参数
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteArticleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SubmitArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitArticleRequest) Reset() {
	*x = SubmitArticleRequest{}
	mi := &file_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitArticleRequest) ProtoMessage() {}

func (x *SubmitArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitArticleRequest.ProtoReflect.Descriptor instead.
func (*SubmitArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubmitArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitArticleResponse) Reset() {
	*x = SubmitArticleResponse{}
	mi := &file_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitArticleResponse) ProtoMessage() {}

func (x *SubmitArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitArticleResponse.ProtoReflect.Descriptor instead.
func (*SubmitArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitArticleResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ReviewArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	ReviewedBy    int64                  `protobuf:"varint,3,opt,name=reviewed_by,json=reviewedBy,proto3" json:"reviewed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewArticleRequest) Reset() {
	*x = ReviewArticleRequest{}
	mi := &file_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewArticleRequest) ProtoMessage() {}

func (x *ReviewArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewArticleRequest.ProtoReflect.Descriptor instead.
func (*ReviewArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{13}
}

func (x *ReviewArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewArticleRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ReviewArticleRequest) GetReviewedBy() int64 {
	if x != nil {
		return x.ReviewedBy
	}
	return 0
}

type ReviewArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewArticleResponse) Reset() {
	*x = ReviewArticleResponse{}
	mi := &file_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewArticleResponse) ProtoMessage() {}

func (x *ReviewArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewArticleResponse.ProtoReflect.Descriptor instead.
func (*ReviewArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{14}
}

func (x *ReviewArticleResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Comment 表示单条评论
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 评论 ID
	ArticleId     int64                  `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章 ID
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户 ID
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                       // 评论内容
	ParentId      int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`    // 父评论 ID（0 表示顶级评论）
	Children      []*Comment             `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`                     // 子评论列表（嵌套回复）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_article_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{15}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *Comment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetChildren() []*Comment {
	if x != nil {
		return x.Children
	}
	return nil
}

// AddCommentRequest 添加评论请求
type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章 ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                       // 评论内容
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`    // 父评论 ID（可选，0 表示顶级评论）
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_article_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{16}
}

func (x *AddCommentRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddCommentRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AddCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// AddCommentResponse 添加评论响应
type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_article_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{17}
}

func (x *AddCommentResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// GetCommentsRequest 获取评论列表请求
type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章 ID
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`       // 页码，默认为 1
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // 每页大小，默认为 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_article_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{18}
}

func (x *GetCommentsRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *GetCommentsRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetCommentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetCommentsResponse 获取评论列表响应
type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"` // 评论列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`      // 总评论数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_article_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{19}
}

func (x *GetCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ViewArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewArticleRequest) Reset() {
	*x = ViewArticleRequest{}
	mi := &file_article_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewArticleRequest) ProtoMessage() {}

func (x *ViewArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewArticleRequest.ProtoReflect.Descriptor instead.
func (*ViewArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{20}
}

func (x *ViewArticleRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ViewArticleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ViewArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Article               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 文章列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewArticleResponse) Reset() {
	*x = ViewArticleResponse{}
	mi := &file_article_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewArticleResponse) ProtoMessage() {}

func (x *ViewArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewArticleResponse.ProtoReflect.Descriptor instead.
func (*ViewArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{21}
}

func (x *ViewArticleResponse) GetData() *Article {
	if x != nil {
		return x.Data
	}
	return nil
}

type LikeArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleRequest) Reset() {
	*x = LikeArticleRequest{}
	mi := &file_article_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleRequest) ProtoMessage() {}

func (x *LikeArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleRequest.ProtoReflect.Descriptor instead.
func (*LikeArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{22}
}

func (x *LikeArticleRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *LikeArticleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnlikeArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"` // 文章 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeArticleRequest) Reset() {
	*x = UnlikeArticleRequest{}
	mi := &file_article_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeArticleRequest) ProtoMessage() {}

func (x *UnlikeArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeArticleRequest.ProtoReflect.Descriptor instead.
func (*UnlikeArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{23}
}

func (x *UnlikeArticleRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *UnlikeArticleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_article_proto protoreflect.FileDescriptor

const file_article_proto_rawDesc = "" +
	"\n" +
	"\rarticle.proto\x12\x02pb\")\n" +
	"\x15ArticleCommonResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\xca\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05state\x18\x06 \x01(\x05R\x05state\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\x03R\tcreatedBy\x12\x1f\n" +
	"\vmodified_by\x18\b \x01(\x03R\n" +
	"modifiedBy\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x12GetArticleResponse\x12\x1f\n" +
	"\x04data\x18\x01 \x01(\v2\v.pb.ArticleR\x04data\"c\n" +
	"\x12GetArticlesRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x03R\x05tagId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"\x84\x01\n" +
	"\x13GetArticlesResponse\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.pb.ArticleR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x19\n" +
	"\bpage_num\x18\x03 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"i\n" +
	"\x19GetPendingArticlesRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\apageNum\x18\x02 \x01(\x03R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\x8b\x01\n" +
	"\x1aGetPendingArticlesResponse\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.pb.ArticleR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x19\n" +
	"\bpage_num\x18\x03 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\x8d\x01\n" +
	"\x11AddArticleRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x03R\x05tagId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x03R\tcreatedBy\"\xce\x01\n" +
	"\x12EditArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vmodified_by\x18\x06 \x01(\x03R\n" +
	"modifiedBy\x12\x14\n" +
	"\x05state\x18\a \x01(\x05R\x05state\x12\x16\n" +
	"\x06userId\x18\b \x01(\x03R\x06userId\">\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"&\n" +
	"\x14SubmitArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\x15SubmitArticleResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"c\n" +
	"\x14ReviewArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x1f\n" +
	"\vreviewed_by\x18\x03 \x01(\x03R\n" +
	"reviewedBy\")\n" +
	"\x15ReviewArticleResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\xb1\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12'\n" +
	"\bchildren\x18\x06 \x03(\v2\v.pb.CommentR\bchildren\"\x82\x01\n" +
	"\x11AddCommentRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"&\n" +
	"\x12AddCommentResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"k\n" +
	"\x12GetCommentsRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"T\n" +
	"\x13GetCommentsResponse\x12'\n" +
	"\bcomments\x18\x01 \x03(\v2\v.pb.CommentR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"L\n" +
	"\x12ViewArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"6\n" +
	"\x13ViewArticleResponse\x12\x1f\n" +
	"\x04data\x18\x01 \x01(\v2\v.pb.ArticleR\x04data\"L\n" +
	"\x12LikeArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"N\n" +
	"\x14UnlikeArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId2\xfb\x06\n" +
	"\x0eArticleService\x12;\n" +
	"\n" +
	"GetArticle\x12\x15.pb.GetArticleRequest\x1a\x16.pb.GetArticleResponse\x12>\n" +
	"\vGetArticles\x12\x16.pb.GetArticlesRequest\x1a\x17.pb.GetArticlesResponse\x12>\n" +
	"\n" +
	"AddArticle\x12\x15.pb.AddArticleRequest\x1a\x19.pb.ArticleCommonResponse\x12@\n" +
	"\vEditArticle\x12\x16.pb.EditArticleRequest\x1a\x19.pb.ArticleCommonResponse\x12D\n" +
	"\rDeleteArticle\x12\x18.pb.DeleteArticleRequest\x1a\x19.pb.ArticleCommonResponse\x12S\n" +
	"\x12GetPendingArticles\x12\x1d.pb.GetPendingArticlesRequest\x1a\x1e.pb.GetPendingArticlesResponse\x12D\n" +
	"\rSubmitArticle\x12\x18.pb.SubmitArticleRequest\x1a\x19.pb.SubmitArticleResponse\x12D\n" +
	"\rReviewArticle\x12\x18.pb.ReviewArticleRequest\x1a\x19.pb.ReviewArticleResponse\x12;\n" +
	"\n" +
	"AddComment\x12\x15.pb.AddCommentRequest\x1a\x16.pb.AddCommentResponse\x12>\n" +
	"\vGetComments\x12\x16.pb.GetCommentsRequest\x1a\x17.pb.GetCommentsResponse\x12>\n" +
	"\vViewArticle\x12\x16.pb.ViewArticleRequest\x1a\x17.pb.ViewArticleResponse\x12@\n" +
	"\vLikeArticle\x12\x16.pb.LikeArticleRequest\x1a\x19.pb.ArticleCommonResponse\x12D\n" +
	"\rUnlikeArtilce\x12\x18.pb.UnlikeArticleRequest\x1a\x19.pb.ArticleCommonResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData []byte
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)))
	})
	return file_article_proto_rawDescData
}

var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_article_proto_goTypes = []any{
	(*ArticleCommonResponse)(nil),      // 0: pb.ArticleCommonResponse
	(*Article)(nil),                    // 1: pb.Article
	(*GetArticleRequest)(nil),          // 2: pb.GetArticleRequest
	(*GetArticleResponse)(nil),         // 3: pb.GetArticleResponse
	(*GetArticlesRequest)(nil),         // 4: pb.GetArticlesRequest
	(*GetArticlesResponse)(nil),        // 5: pb.GetArticlesResponse
	(*GetPendingArticlesRequest)(nil),  // 6: pb.GetPendingArticlesRequest
	(*GetPendingArticlesResponse)(nil), // 7: pb.GetPendingArticlesResponse
	(*AddArticleRequest)(nil),          // 8: pb.AddArticleRequest
	(*EditArticleRequest)(nil),         // 9: pb.EditArticleRequest
	(*DeleteArticleRequest)(nil),       // 10: pb.DeleteArticleRequest
	(*SubmitArticleRequest)(nil),       // 11: pb.SubmitArticleRequest
	(*SubmitArticleResponse)(nil),      // 12: pb.SubmitArticleResponse
	(*ReviewArticleRequest)(nil),       // 13: pb.ReviewArticleRequest
	(*ReviewArticleResponse)(nil),      // 14: pb.ReviewArticleResponse
	(*Comment)(nil),                    // 15: pb.Comment
	(*AddCommentRequest)(nil),          // 16: pb.AddCommentRequest
	(*AddCommentResponse)(nil),         // 17: pb.AddCommentResponse
	(*GetCommentsRequest)(nil),         // 18: pb.GetCommentsRequest
	(*GetCommentsResponse)(nil),        // 19: pb.GetCommentsResponse
	(*ViewArticleRequest)(nil),         // 20: pb.ViewArticleRequest
	(*ViewArticleResponse)(nil),        // 21: pb.ViewArticleResponse
	(*LikeArticleRequest)(nil),         // 22: pb.LikeArticleRequest
	(*UnlikeArticleRequest)(nil),       // 23: pb.UnlikeArticleRequest
}
var file_article_proto_depIdxs = []int32{
	1,  // 0: pb.GetArticleResponse.data:type_name -> pb.Article
	1,  // 1: pb.GetArticlesResponse.data:type_name -> pb.Article
	1,  // 2: pb.GetPendingArticlesResponse.data:type_name -> pb.Article
	15, // 3: pb.Comment.children:type_name -> pb.Comment
	15, // 4: pb.GetCommentsResponse.comments:type_name -> pb.Comment
	1,  // 5: pb.ViewArticleResponse.data:type_name -> pb.Article
	2,  // 6: pb.ArticleService.GetArticle:input_type -> pb.GetArticleRequest
	4,  // 7: pb.ArticleService.GetArticles:input_type -> pb.GetArticlesRequest
	8,  // 8: pb.ArticleService.AddArticle:input_type -> pb.AddArticleRequest
	9,  // 9: pb.ArticleService.EditArticle:input_type -> pb.EditArticleRequest
	10, // 10: pb.ArticleService.DeleteArticle:input_type -> pb.DeleteArticleRequest
	6,  // 11: pb.ArticleService.GetPendingArticles:input_type -> pb.GetPendingArticlesRequest
	11, // 12: pb.ArticleService.SubmitArticle:input_type -> pb.SubmitArticleRequest
	13, // 13: pb.ArticleService.ReviewArticle:input_type -> pb.ReviewArticleRequest
	16, // 14: pb.ArticleService.AddComment:input_type -> pb.AddCommentRequest
	18, // 15: pb.ArticleService.GetComments:input_type -> pb.GetCommentsRequest
	20, // 16: pb.ArticleService.ViewArticle:input_type -> pb.ViewArticleRequest
	22, // 17: pb.ArticleService.LikeArticle:input_type -> pb.LikeArticleRequest
	23, // 18: pb.ArticleService.UnlikeArtilce:input_type -> pb.UnlikeArticleRequest
	3,  // 19: pb.ArticleService.GetArticle:output_type -> pb.GetArticleResponse
	5,  // 20: pb.ArticleService.GetArticles:output_type -> pb.GetArticlesResponse
	0,  // 21: pb.ArticleService.AddArticle:output_type -> pb.ArticleCommonResponse
	0,  // 22: pb.ArticleService.EditArticle:output_type -> pb.ArticleCommonResponse
	0,  // 23: pb.ArticleService.DeleteArticle:output_type -> pb.ArticleCommonResponse
	7,  // 24: pb.ArticleService.GetPendingArticles:output_type -> pb.GetPendingArticlesResponse
	12, // 25: pb.ArticleService.SubmitArticle:output_type -> pb.SubmitArticleResponse
	14, // 26: pb.ArticleService.ReviewArticle:output_type -> pb.ReviewArticleResponse
	17, // 27: pb.ArticleService.AddComment:output_type -> pb.AddCommentResponse
	19, // 28: pb.ArticleService.GetComments:output_type -> pb.GetCommentsResponse
	21, // 29: pb.ArticleService.ViewArticle:output_type -> pb.ViewArticleResponse
	0,  // 30: pb.ArticleService.LikeArticle:output_type -> pb.ArticleCommonResponse
	0,  // 31: pb.ArticleService.UnlikeArtilce:output_type -> pb.ArticleCommonResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
